// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzAkwgc7bFhat0eL1P9y4j1ptEwaTPqNU',
    appId: '1:266230068696:web:db2a4091083558b273aead',
    messagingSenderId: '266230068696',
    projectId: 'com-agafielite-stage',
    authDomain: 'com-agafielite-stage.firebaseapp.com',
    storageBucket: 'com-agafielite-stage.firebasestorage.app',
    measurementId: 'G-MBF4J0J4X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA-p3ZBTSMWJh-l27_wzE_OUaSgzDlIY4',
    appId: '1:266230068696:android:bd45b8f0dee979b773aead',
    messagingSenderId: '266230068696',
    projectId: 'com-agafielite-stage',
    storageBucket: 'com-agafielite-stage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhea4-Xka6mdLzDXV49u3OZS6nNmTkarA',
    appId: '1:266230068696:ios:783f2cb789d1ee1d73aead',
    messagingSenderId: '266230068696',
    projectId: 'com-agafielite-stage',
    storageBucket: 'com-agafielite-stage.firebasestorage.app',
    iosBundleId: 'com.mikkyboy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhea4-Xka6mdLzDXV49u3OZS6nNmTkarA',
    appId: '1:266230068696:ios:ed82a895c8bfdd4f73aead',
    messagingSenderId: '266230068696',
    projectId: 'com-agafielite-stage',
    storageBucket: 'com-agafielite-stage.firebasestorage.app',
    iosBundleId: 'com.agafielite.stage',
  );
}
